[package]
name = "fyfth_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2" }
bevy_egui = "0.29.0"
fyfth_core = { path = "../fyfth_core" }
fyfth_focus = { path = "../fyfth_focus" }
