[package]
name = "fyfth_core"
version = "0.1.0"
edition = "2021"

[features]
regex = ["dep:regex"]

[dependencies]
bevy = { version = "0.14.2", default-features = false }
regex = { version = "1.11.0", optional = true }
